'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NetGate.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Public ReadOnly Property CaptionError() As String
            Get
                Return ResourceManager.GetString("CaptionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information.
        '''</summary>
        Public ReadOnly Property CaptionInformation() As String
            Get
                Return ResourceManager.GetString("CaptionInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning.
        '''</summary>
        Public ReadOnly Property CaptionWarning() As String
            Get
                Return ResourceManager.GetString("CaptionWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not connect to remote server..
        '''</summary>
        Public ReadOnly Property CouldNotConnectToRemoteServer() As String
            Get
                Return ResourceManager.GetString("CouldNotConnectToRemoteServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not connect to one or more services..
        '''</summary>
        Public ReadOnly Property CouldNotConnectToService() As String
            Get
                Return ResourceManager.GetString("CouldNotConnectToService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error connecting server: .
        '''</summary>
        Public ReadOnly Property ErrorConnectingServer() As String
            Get
                Return ResourceManager.GetString("ErrorConnectingServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Incorrect username or password..
        '''</summary>
        Public ReadOnly Property IncorrectUsernameOrPassword() As String
            Get
                Return ResourceManager.GetString("IncorrectUsernameOrPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server identifier is missing..
        '''</summary>
        Public ReadOnly Property ServerIdIsMissing() As String
            Get
                Return ResourceManager.GetString("ServerIdIsMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is an empty field!.
        '''</summary>
        Public ReadOnly Property ThereIsEmptyField() As String
            Get
                Return ResourceManager.GetString("ThereIsEmptyField", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This service is not active!.
        '''</summary>
        Public ReadOnly Property ThisServiceIsNotActive() As String
            Get
                Return ResourceManager.GetString("ThisServiceIsNotActive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable resolve address of .
        '''</summary>
        Public ReadOnly Property UnableToResolveAddress() As String
            Get
                Return ResourceManager.GetString("UnableToResolveAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown token:.
        '''</summary>
        Public ReadOnly Property UnknownToken() As String
            Get
                Return ResourceManager.GetString("UnknownToken", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must restart for changes to take effect..
        '''</summary>
        Public ReadOnly Property YouMustRestartForChangesToTakeEffect() As String
            Get
                Return ResourceManager.GetString("YouMustRestartForChangesToTakeEffect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must select different interfaces..
        '''</summary>
        Public ReadOnly Property YouMustSelectDifferentInterfaces() As String
            Get
                Return ResourceManager.GetString("YouMustSelectDifferentInterfaces", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must select one interface..
        '''</summary>
        Public ReadOnly Property YouMustSelectOneInterface() As String
            Get
                Return ResourceManager.GetString("YouMustSelectOneInterface", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must select one of the availble interfaces. Do you want to select &lt;0.0.0.0&gt; ?.
        '''</summary>
        Public ReadOnly Property YouMustSelectOneOfTheAvailbleInterfaces() As String
            Get
                Return ResourceManager.GetString("YouMustSelectOneOfTheAvailbleInterfaces", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
